// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClr5drhbraadHZjZXDZjefDjz7DNRkJM0',
    appId: '1:290624247247:web:fddc69bc2f8fb80fbdaeba',
    messagingSenderId: '290624247247',
    projectId: 'habit-timer-c690a',
    authDomain: 'habit-timer-c690a.firebaseapp.com',
    storageBucket: 'habit-timer-c690a.firebasestorage.app',
    measurementId: 'G-DZ45E416J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-XG-UDkGhJGP3LXGQptBLzkBcihQmD2U',
    appId: '1:290624247247:android:6b4e85be2012b552bdaeba',
    messagingSenderId: '290624247247',
    projectId: 'habit-timer-c690a',
    storageBucket: 'habit-timer-c690a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgPMoPWoJA5MKvzThBgrPpFiaHWbVbDIU',
    appId: '1:290624247247:ios:d0ad63e0b0177f11bdaeba',
    messagingSenderId: '290624247247',
    projectId: 'habit-timer-c690a',
    storageBucket: 'habit-timer-c690a.firebasestorage.app',
    iosClientId: '290624247247-b6jeh1kcvblh0ls2fsmemkronbgh729g.apps.googleusercontent.com',
    iosBundleId: 'com.test.myFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgPMoPWoJA5MKvzThBgrPpFiaHWbVbDIU',
    appId: '1:290624247247:ios:d0ad63e0b0177f11bdaeba',
    messagingSenderId: '290624247247',
    projectId: 'habit-timer-c690a',
    storageBucket: 'habit-timer-c690a.firebasestorage.app',
    iosClientId: '290624247247-b6jeh1kcvblh0ls2fsmemkronbgh729g.apps.googleusercontent.com',
    iosBundleId: 'com.test.myFlutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClr5drhbraadHZjZXDZjefDjz7DNRkJM0',
    appId: '1:290624247247:web:47379519a6777eacbdaeba',
    messagingSenderId: '290624247247',
    projectId: 'habit-timer-c690a',
    authDomain: 'habit-timer-c690a.firebaseapp.com',
    storageBucket: 'habit-timer-c690a.firebasestorage.app',
    measurementId: 'G-VFZEBJ8Y2J',
  );
}
